FROM docker.elastic.co/beats/metricbeat:7.1.1
COPY ./config/metricbeat.yml /usr/share/metricbeat/metricbeat.yml
USER root
RUN chown root:metricbeat /usr/share/metricbeat/metricbeat.yml
RUN chmod go-w /usr/share/metricbeat/metricbeat.yml



# ARG ELK_VERSION

# FROM docker.elastic.co/beats/filebeat:7.1.1
# # FROM docker.elastic.co/beats/filebeat:7.1.1
# USER root
# COPY ./config/filebeat.yml /usr/share/filebeat/filebeat.yml
# RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
# RUN chmod go-w /usr/share/filebeat/filebeat.yml